sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zyt1566585M
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9jxdTFEmLPvSi1nzyJ
    access-key-secret: YQ3obBowF6n6MXHsjnehdkWB4OyMjK
    bucket-name: zyt-sky
